osy9536/ssafy_algo_study

- algorithm/src/ohseyoung/b1920.java
- algorithm/src/ohseyoung/b2343.java
> (토)1920번+ (일)2343번

- algorithm/src/junseo/b14719.java
- algorithm/src/junseo/b1644.java
- algorithm/src/junseo/b2003.java
- algorithm/src/junseo/b2798.java
> 이준서_(1644)

- algorithm/src/minho/b2447.java
- algorithm/src/minho/b4779.java
> 정민호_(4779)

- algorithm/src/ohseyoung/b2110.java
답을 보고야 이해했읍니다,,,
다음에 또 한번 도전해야 할 문제...!!
> 오세영_(2110)

- algorithm/src/daeyoung/b12015.java
구현 로직 서치 해서 풀었습니다.
풀이과정을 참고한 블로그와 함께 포스팅 했으니까 관련 문제 푸시는 분 들어가서 참고 하시면 좋을거 같아요.
https://kdozlo.tistory.com/29
> 김대영_(12015)

- algorithm/src/jaeyun/b01620.java
HashMap 자료구조 관련 문제입니다. (물론 이분탐색으로도 가능합니다)
[이런](https://www.acmicpc.net/source/63994602) 풀이도 있네요...
> 이재윤_(1620)

- algorithm/src/jaeyun/b13414.java
지금까지 Scanner로 입력받았는데, [이 문제](https://www.acmicpc.net/status?problem_id=13414&user_id=jy1277)에서 BufferedReader 사용법도 알아야겠다는 생각이 들어서 공유합니다. 시간 차이가 꽤 나네요
> 이재윤_(13414)

- algorithm/src/daeyoung/b2559.java
- algorithm/src/daeyoung/b6566.java
자료구조 선택의 중요성을 알려주는 좋은 문제 같습니다! 추천 해주신 세영이형 감사합니다 ! 👍
> 김대영_(2559, 6566)

- algorithm/src/daeyoung/b1205.java
문제 로직은 쉬운데 bufferedReader랑 StringTokenizer로 풀면 마지막쯤에서 런타임 에러를 만나게 되는데 그게 나중에 도움 될거 같아서 추천 드립니다. 늦게 시작해서 빨리 풀려고 선택했는데 에러 잡는다고 결국 지각 했네요...
> 김대영_(1205)

- algorithm/src/soomin/b1158.java
- algorithm/src/soomin/b2167.java
StringTokenizer 중복 되도록 안 쓰고 모든 입력 한번에 받는 법이 있을까요?
> 전수민_(2167, 1158)

- algorithm/src/ohseyoung/b1016.java
> 오세영_(1016)

- algorithm/src/daeyoung/b1016.java
문제 추천해 주신 세영이형 감사합니다.
이 문제 덕분에 에라토스테네스의 체 로직 완전 이해했습니다.
런타임 에러 몇번이나 났는지 모르겠네요...
> 김대영_(1016)

- algorithm/src/daeyoung/b2467.java
투포인터로 풀었는데 이진탐색으로도 할 수 있다고 해서 내일은 이진탐색으로 한번 더 풀어볼 예정 입니다.
> 김대영_(2467)

- algorithm/src/daeyoung/b2023.java
필요한 자리수에서 내려가는 형식으로 로직 짰는데 런타임 에러 나서 결국 힌트를 듣고 풀었습니다.. 아직 많이 부족하네요!
> 김대영_(2023)

- algorithm/src/soomin/b12891.java
- algorithm/src/soomin/b2961.java
저는 큐로 풀었는데, Hash Map으로 푼 풀이를 보니 훨씬 가독성도 좋고 중복도 없었습니다. 
다음에 기억 안 날 때 쯤 다시 풀어보겠습니다.
> 전수민_(12891)

- algorithm/src/soomin/b16435.java
- algorithm/src/soomin/b16935.java
- algorithm/src/soomin/b17406.java
- algorithm/src/soomin/b20546.java
- algorithm/src/soomin/b2578.java
- algorithm/src/soomin/b2839.java
어제꺼가 승인 미달로 merge 안되서 어제것에 겹쳐서 올립니다요
> 전수민_(b2839,b16435,b16935,b17406,b2578,b20546)

- algorithm/src/chaesong/b1012.java
- algorithm/src/chaesong/b1654.java
- algorithm/src/chaesong/b2606.java
- algorithm/src/daeyoung/b1074.java
- algorithm/src/jisu/b2630.java
- algorithm/src/jisu/b2805.java
- algorithm/src/ohseyoung/b1012.java
- algorithm/src/ohseyoung/b1074.java
- algorithm/src/ohseyoung/b20187.java
혹시 저번 커밋에서 마지막 한 줄 추가 해달라고 하신 이유가 무엇인가요??
> 최지수_2630, 2805

- algorithm/src/jisu/b1028.java
- algorithm/src/jisu/b11725.java
- algorithm/src/jisu/b2740.java
- algorithm/src/jisu/b5525.java
- algorithm/src/jisu/b9019.java
저번 pr에 문제가 생겨서 지우고 다시 올립니다 (+ 주말 문제도 함께)
> 최지수_1028,11725,9019,5525,2740

- algorithm/src/minho/b11403.java
- algorithm/src/minho/b16236.java
- algorithm/src/minho/b2178.java
- algorithm/src/minho/b9375.java
- algorithm/src/soomin/b11403.java
- algorithm/src/soomin/b16401.java
> 정민호_(2178,9375,16236,11403)

- algorithm/src/soomin/b11053.java
- algorithm/src/soomin/b11663.java
- algorithm/src/soomin/b12761.java
- algorithm/src/soomin/b12865.java
- algorithm/src/soomin/b14502.java
- algorithm/src/soomin/b1654.java
- algorithm/src/soomin/b1920.java
- algorithm/src/soomin/b19637.java
- algorithm/src/soomin/b2239.java
- algorithm/src/soomin/b22871.java
- algorithm/src/soomin/b2805.java
> 전수민_(11663)

- algorithm/src/soomin/b1015.java
- algorithm/src/soomin/b10828.java
- algorithm/src/soomin/b10845.java
- algorithm/src/soomin/b10866.java
- algorithm/src/soomin/b1107.java
- algorithm/src/soomin/b11404.java
- algorithm/src/soomin/b12015.java
- algorithm/src/soomin/b1259.java
- algorithm/src/soomin/b12738.java
- algorithm/src/soomin/b12920.java
- algorithm/src/soomin/b15686.java
- algorithm/src/soomin/b1786.java
- algorithm/src/soomin/b1927.java
- algorithm/src/soomin/b2458.java
- algorithm/src/soomin/b3055.java
- algorithm/src/soomin/b3079.java
- algorithm/src/soomin/b4153.java
- algorithm/src/soomin/b7576.java
- algorithm/src/soomin/b7662.java
- algorithm/src/soomin/b9205.java
…, 3055: 탈출, 3079: 입국심사, 4153: 직각삼각형, 7576: 토마토, 7662: 이중 우선순위 큐, 9205: 맥주 마시면서 걸어가기, 10828: 스택, 10845: 큐, 10866: 덱, 11404: 플로이드, 12015: 가장 긴 증가하는 부분수열 2, 12738: 가장 긴 증가하는 부분수열 3, 12920: 평범한 배낭, 15686: 치킨 배달
> 전수민_(1015, 1107, 1259, 1786, 1927, 2458, 3055, 3079, 4153, 7576, 7662,  9205, 10828, 10845, 10866, 11404, 12015, 12738, 12920, 15686)

- algorithm/src/minho/b17472.java
- algorithm/src/minho/b9205.java
- algorithm/src/minho/s7465.java
> 정민호_1010_(s7465,9205,17472)

- algorithm/src/minho/b17144.java
https://geishastory.tistory.com/2
> 정민호_1011_b17144

- algorithm/src/chaesong/b1309.java
> 윤채송_1016_b1309

- algorithm/src/minho/b2206.java
https://geishastory.tistory.com/9
> 정민호_1016_b2206

- algorithm/src/chaesong/p베스트앨범
> 윤채송_1017_p베스트앨범

- algorithm/src/minho/b13549.java
https://geishastory.tistory.com/11
> 정민호_1017_b13549

- algorithm/src/minho/b1916.java
https://geishastory.tistory.com/12
> 정민호_1020_b1916

- algorithm/src/minho/b1446.java
https://geishastory.tistory.com/13
> 정민호_1021_b1446

- algorithm/src/minho/b1238.java
https://geishastory.tistory.com/15
> 정민호_1024_b1238

- algorithm/src/minho/p_불량사용자.java
https://geishastory.tistory.com/17
> 정민호_1025_p불량사용자

- algorithm/src/chaesong/p타겟넘버.java
> 윤채송_1031_p타겟넘버

- algorithm/src/minho/b14284.java
https://geishastory.tistory.com/21
> 정민호_1101_b14284

- algorithm/src/ohseyoung/b1967.java
실수로 마스터에 넣어서 조금만 수정하고 재 업로드 합니다 ㅜ
> 오세영_0103_b1967

- algorithm/src/soomin/b2108.java
- algorithm/src/soomin/b25192.java
- algorithm/src/soomin/b26069.java
전수민_0121_b26069
전수민_0121_b25192
> 전수민_0115_0121

- algorithm/src/ohseyoung/b10844.java
- algorithm/src/ohseyoung/b11057.java
- algorithm/src/ohseyoung/b1486.java
등산 : 메모리 초과 못잡아서 답지봄
쉬운 계단 수 : 실버지만 dp 어렵다 답지봄
>  오세영_0304_0310

- algorithm/src/soomin/b14889.java
- algorithm/src/soomin/b2589.java
- algorithm/src/soomin/b2667.java
- algorithm/src/soomin/b5430.java
boj 2589 보물섬
boj  2667 단지 번호 붙이기 
boj 5430 AC
boj 14889 스타트와링크
> 전수민_0311_보물섬

- algorithm/src/soomin/b1038.java
- algorithm/src/soomin/b14500.java
- algorithm/src/soomin/b14503.java
- algorithm/src/soomin/b1676.java
- algorithm/src/soomin/b1676최적화_시도.java
- algorithm/src/soomin/b2589 (2).java
- algorithm/src/soomin/b3085.java
> 전수민_0408_0414
